name: Deploy cloudformation

on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-252517e166d077101f88a33397bd-prodbucket-1m4kifgmpg3i4
      
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: Prueba
          template: example.yaml
      - name: Test deploy
        uses: cosq-network/aws-cloudformation-deploy@v1.1.0
        with:
          stackName: Prueba
          templateFile: example.yaml
          hasIAMCapability: true
          hasIAMNamedCapability: true
